modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/BasiqueEvangelist/FlashFreeze/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "flashfreeze_testmod"
version = "${version}"
displayName = "FlashFreeze (Test mod)"
authors = "BasiqueEvangelist"
description = '''
Keep unknown blocks and items
'''

[[dependencies.flashfreeze_testmod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flashfreeze_testmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flashfreeze_testmod]]
modId = "flashfreeze"
mandatory = true
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "BOTH"